type Query {
    allApplications: [Application!]!
    application(id: String): Application
    applicationClientId(id: String): String
}
type Mutation {
    updateApplication(id: String, data: ApplicationPatch): Application
    newApplication(
        name: String,
        type: ApplicationType
    ): Application
    deleteApplication(id: String): Boolean!
    resetApplicationClientId(id: String): String
}

type Application {
    id: ID!
    name: String!
    type: ApplicationType!
    avatar_url: String
    redirect_uris: [String!]!
}
input ApplicationPatch {
    name: String
    #type: ApplicationType
    avatar_url: String
    redirect_uris: [String!]
}
enum ApplicationType {
    CLIENT
    BOT
}