markdown: kramdown

url: https://getaqua.github.io/
base_url: /gridless
#site_url: http://127.0.0.1:4000
title: Gridless
navlogo: /assets/img/logo-nav.png
icon: /assets/img/favicon.png
brand_font: DM Sans
brand_colors: 
  - "#56CCF2" # Light Aqua
  - "#673AB7" # Pure Purple (accent color)
  - "#2D9CDB" # Medium Aqua
  - "#2F80ED" # Deep Aqua

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
permalink: /:categories/:slug/