source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"
#gem "jekyll-paginate-v2", "~> 3.0.0"
#gem "jekyll-feed", "~> 0.15.1"
gem "github-pages", "~> 214"
#gem "rake", "~> 12.3.1"
#gem "slugify", "~> 1.0"
